class CreateKscTable < ActiveRecord::Migration
  def change
    create_table :kepler_targets do |t|
      t.integer	"kepid"
      t.string	"tm_designation"
      t.integer	"nkoi"
      t.float	"kepmag"
      t.integer	"teff"
      t.float	"logg"
      t.float	"feh"
      t.float	"radius"
      t.float	"mass"
      t.float	"dens"
      t.float	"jmag"
      t.float	"hmag"
      t.float	"kmag"
      t.float	"ra"
      t.float	"dec"
      t.float	"i1mag"
      t.float	"i1err"
      t.float	"i2mag"
      t.float	"i2err"
      t.integer	"i1obs"
      t.integer	"i2obs"
      t.float	"ukirtj"
      t.float	"w1mag"
      t.float	"w1err"
      t.float	"w2mag"
      t.float	"w2err"
      t.float	"i1_i2"
      t.float	"ukj_i2"
      t.float	"j_i2"
      t.float	"w1_w2"
    end
  end
end
